### ISSUE TITLE
YOUR example doesn't work

### ISSUE THREAD

**Issue by VadimS20** [knordman/esstee#1]
build/program-tester --file="src/tests/programs/example.ST" --program="testprgm" --pre-run-queries="testprgm.a:=10*5+1" --post-run-queries="testprgm.a" 
loading 'src/tests/programs/example.ST' ... ok
running pre queries
reference to undefined variable 'testprgm'
@ L(1313147451:1313147451) C(1096179524:1096179532)

**Comment by knordman** [comment]
Thank you for the first issue! :1st_place_medal: :smile: 

You're right, it seemed I updated the syntax and forgot to update the README, but fixed now. To refer to a program's variables one should use [program-name]. 

For convenience, here's the working example:
```
./build/program-tester --file="src/tests/programs/example.ST" --program="testprgm" --pre-run-queries="[testprgm].a:=10*5+1" --post-run-queries="[testprgm].a"
```

As you might've seen from the git log, this project has been collecting dust for some years, but perhaps time to do something about it :slightly_smiling_face:
